//
//  MessagesRouter.swift
//  Pods
//
//  Created Анастасия Здобнова on 23.11.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Dastan Makhutov @mchutov
//

import UIKit

public class MessagesRouter: MessagesWireframeProtocol {
    weak var viewController: UIViewController?

    public static func createModule() -> UIViewController {
        let view = MessagesViewController()
        let interactor = MessagesInteractor()
        let router = MessagesRouter()
        let presenter = MessagesPresenter(
            interface: view,
            interactor: interactor,
            router: router
        )

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
