//
//  MessagesPresenter.swift
//  Pods
//
//  Created Анастасия Здобнова on 23.11.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Dastan Makhutov @mchutov
//

import UIKit

final class MessagesPresenter {
    var interactor: MessagesInteractorProtocol?
    weak private var view: MessagesViewProtocol?
    private let router: MessagesWireframeProtocol

    init(interface: MessagesViewProtocol, 
         interactor: MessagesInteractorProtocol?,
         router: MessagesWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}

extension MessagesPresenter: MessagesPresenterProtocol {
    func getNumberOfMessages() -> Int {
        return 1
    }
}
