//
//  MessagesProtocols.swift
//  Pods
//
//  Created Анастасия Здобнова on 23.11.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Dastan Makhutov @mchutov
//

import Foundation

//MARK: Wireframe -
protocol MessagesWireframeProtocol: AnyObject {

}
//MARK: Presenter -
protocol MessagesPresenterProtocol: AnyObject {
    func getNumberOfMessages() -> Int
}

//MARK: Interactor -
protocol MessagesInteractorProtocol: AnyObject {
  var presenter: MessagesPresenterProtocol?  { get set }
}

//MARK: View -
protocol MessagesViewProtocol: AnyObject {
  var presenter: MessagesPresenterProtocol?  { get set }
}
